import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Link } from "react-router-dom";
import { Calendar, Users, Clock, MapPin, Check } from "lucide-react";
export default function BookingSuccess({ confirmedBooking, restaurant, date, slot, guests }) {
    if (!confirmedBooking || !restaurant)
        return null;
    return (_jsxs("div", { className: "max-w-xl w-full bg-white border border-outline-variant/20 p-10 text-center rounded-lg ambient-shadow space-y-8 animate-in zoom-in-95 duration-300", children: [_jsx("div", { className: "w-16 h-16 bg-secondary/15 rounded-full flex items-center justify-center text-secondary mx-auto", children: _jsx(Check, { size: 32 }) }), _jsxs("div", { className: "space-y-3", children: [_jsx("h2", { className: "font-display text-3xl font-medium text-primary", children: "Reservation Confirmed" }), _jsxs("p", { className: "text-xs text-black/55 max-w-sm mx-auto leading-relaxed", children: ["A curated dining experience has been successfully reserved for you at", " ", _jsx("span", { className: "text-primary", children: restaurant.name }), "."] })] }), _jsxs("div", { className: "bg-surface-container-low p-6 rounded-md space-y-4 text-left border border-outline-variant/10", children: [_jsxs("div", { className: "flex justify-between items-center pb-3 border-b border-outline-variant/10", children: [_jsx("span", { className: "text-[10px] font-medium text-black/55 tracking-wider uppercase", children: "REFERENCE CODE" }), _jsx("span", { className: "text-sm font-medium text-secondary", children: confirmedBooking.bookingId })] }), _jsxs("div", { className: "space-y-3 text-xs text-on-surface", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Calendar, { size: 14, className: "text-black/55" }), _jsx("span", { children: new Date(date).toLocaleDateString("en-US", {
                                            weekday: "long",
                                            year: "numeric",
                                            month: "long",
                                            day: "numeric",
                                        }) })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Clock, { size: 14, className: "text-black/55" }), _jsxs("span", { children: [slot, " PM"] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Users, { size: 14, className: "text-black/55" }), _jsxs("span", { children: [guests, " Guests"] })] }), _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(MapPin, { size: 14, className: "text-black/55 mt-0.5" }), _jsx("span", { children: restaurant.address })] })] })] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 pt-4", children: [_jsx(Link, { to: "/dashboard", className: "flex-1 bg-primary hover:bg-primary-container text-white py-3.5 px-4 text-xs font-medium tracking-widest uppercase hover:text-secondary text-center cursor-pointer transition-colors", children: "MY BOOKINGS" }), _jsx(Link, { to: "/", className: "flex-1 border border-outline-variant/50 hover:border-primary text-primary py-3.5 px-4 text-xs font-medium tracking-widest uppercase text-center cursor-pointer transition-colors", children: "DISCOVER MORE" })] })] }));
}
